# Generated by Django 6.0 on 2025-12-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('user_id', models.IntegerField(help_text='ID użytkownika z auth-service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
